name: concurrency run
on: workflow_dispatch

jobs:
  job-1:
    runs-on: ubuntu-latest
    concurrency:
      group: example-group
      cancel-in-progress: true
    steps:
    - name: print
      run: echo "job 1"
  job2:   
    runs-on: ubuntu-latest
    concurrency:
      group: example-group
      cancel-in-progress: true
    steps:
    - name: print
      run: echo "job 2"
  job3:   
    runs-on: ubuntu-latest
    concurrency:
      group: example-group
      cancel-in-progress: false
    steps:
    - name: print
      run: echo "job 2"
  
  job4:   
    runs-on: ubuntu-latest
    concurrency:
      group: example-group
      cancel-in-progress: false
    steps:
    - name: print
      run: echo "job 2"
  
