name: concurrency run
on: workflow_dispatch

jobs:
  job-1:
    if: always()
    runs-on: ubuntu-latest
    concurrency:
      group: example-group
      cancel-in-progress: false
    steps:
    - name: print
      run: echo "job 1"
  job2:   
    if: always()
    runs-on: ubuntu-latest
    concurrency:
      group: example-group
      cancel-in-progress: false
    steps:
    - name: print
      run: echo "job 2"
  job3: 
    if: always()
    runs-on: ubuntu-latest
    concurrency:
      group: example-group
      cancel-in-progress: false
    steps:
    - name: print
      run: echo "job 2"
  
  job4:  
    if: always()
    runs-on: ubuntu-latest
    concurrency:
      group: example-group
      cancel-in-progress: false
    steps:
    - name: print
      run: echo "job 2"
  
