name: Docker Image CI

on:
 workflow_dispatch:
 
jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t amzaon_ecs/sourabh . 

    - name: hehe
      uses: docker/login-action@v2
      with:
         username: sgulhane
         password: dckr_pat_V0RvQkYrFBDUdwO8dtcOf_M6IWg
    - name: docker push
      run : |
          docker images
          docker tag amzaon_ecs/sourabh  sgulhane/automation:latest
          docker images
          docker push sgulhane/automation:latest
